### ISSUE TITLE
Set up Auth and start fetching data

### ISSUE THREAD

**Issue by 1298se** [dave2000sang/Trackuriboh-server#5]
Use client secret to start fetching data from tcgplayer

**Comment by dave2000sang** [comment]
TODOs
- [X] Get API access token
- [ ] Fetch CardSets
- [ ] Fetch Products
- [ ] Fetch Prices

**Comment by dave2000sang** [comment]
Potential Improvements
- Pass the access token as param to handlers, https://stackoverflow.com/questions/34046194/how-to-pass-arguments-to-router-handlers-in-golang-using-gin-web-framework
